version: '3'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE_URL=jdbc:postgresql://pgludoapp.postgres.database.azure.com:5432/postgres?sslmode=require
    ports:
      - "8080:8080"